spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
server:
  servlet:
    context-path: /cliente


#spring:
#  application:
#    name: clientes
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/cliente
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect